src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    private $plainPassword;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
         $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function __toString()
    {
        return "{$this->getFirstName()}";
    }

    /**
     * @return mixed
     */
    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    /**
     * @param mixed $plainPassword
     */
    public function setPlainPassword($plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }


}

src/Controller/EasyAdmin/UserController.php
<?php


namespace App\Controller\EasyAdmin;


use App\Entity\User;
use EasyCorp\Bundle\EasyAdminBundle\Controller\EasyAdminController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class UserController extends EasyAdminController
{
    /**
     * @var UserPasswordEncoderInterface
     */
    private $userPasswordEncoder;

    /**
     * UserController constructor.
     */
    public function __construct(UserPasswordEncoderInterface $userPasswordEncoder)
    {
        $this->userPasswordEncoder = $userPasswordEncoder;
    }

    /**
     * @param User $entity
     */
    protected function updateEntity($entity)
    {
        // update the password if necessary
        if (!empty($entity->getPlainPassword())) {
            $entity->setPassword($this->userPasswordEncoder->encodePassword($entity, $entity->getPlainPassword()));
            $entity->eraseCredentials();
        }

        parent::updateEntity($entity);
    }

    protected function persistEntity($entity)
    {
        // update the password if necessary
        if (!empty($entity->getPlainPassword())) {
            $entity->setPassword($this->userPasswordEncoder->encodePassword($entity, $entity->getPlainPassword()));
            $entity->eraseCredentials();
        }

        parent::persistEntity($entity);
    }


}

src/Controller/PublicHomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class PublicHomeController extends AbstractController
{
    /**
     * @Route("/", name="public_home")
     */
    public function index()
    {
        return $this->render('public_home/index.html.twig', [
            'controller_name' => 'PublicHomeController',
        ]);
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    /**
     * @Route("/login", name="login", methods={"GET", "POST"})
     */
    public function login(AuthenticationUtils $authenticationUtils)
    {
        if ($this->getUser()) {
            return $this->redirectToRoute('public_home');
        }
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();

        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', [
            'last_username' => $lastUsername,
            'error'         => $error,
        ]);
    }

    /**
     * @Route("/logout", name="logout", methods={"GET"})
     */
    public function logout()
    {
        // controller can be blank: it will never be executed!
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}
    </head>
    <body>
        <div class="uk-navbar-container uk-active uk-container-expand uk-sticky-fixed">
            <nav class="uk-navbar">
                <div class="uk-navbar-left">
                    <a href="{{ path('public_home') }}" class="uk-navbar-item uk-logo">
                        {{ app_name }}
                    </a>




                    {% if app.user %}

                    <ul class="uk-navbar-nav">
                            <li class="uk-active">
                                <a href="{{ path('easyadmin') }}">Admin</a>
                            </li>
                    </ul>

                    {% endif %}
                </div>

                <div class="uk-navbar-right">
                    {% if app.user %}
                        <ul class="uk-navbar-nav">
                            <li class="uk-active">
                                <a href="#">{{ app.user.firstName }} &nbsp;<span uk-icon="chevron-down"></span></a>
                                <div uk-dropdown="pos: bottom-right; mode: click; offset: -17;">
                                    <ul class="uk-nav uk-navbar-dropdown-nav">
                                        <li class="uk-nav-header">{% trans %}Actions{% endtrans %}</li>
                                        <li><a href="{{ path('logout') }}">{% trans %}Logout{% endtrans %}</a></li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    {% else %}
                        <ul class="uk-navbar-nav">
                            <li><a href="{{ path('login') }}">{% trans %}Login{% endtrans %}</a></li>
                        </ul>

                    {% endif %}
                </div>
            </nav>
        </div>
        <main class="uk-container uk-container-expand">
            {% block body %}{% endblock %}
        </main>

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}

    </body>
</html>

templates/public_home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PublicHomeController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/home/jmp/src/sheldon/src/Controller/PublicHomeController.php'|file_link(0) }}">src/Controller/PublicHomeController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/home/jmp/src/sheldon/templates/public_home/index.html.twig'|file_link(0) }}">templates/public_home/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {% trans %}Login{% endtrans %}
{% endblock %}


{% block body %}

    <div class="uk-flex uk-flex-center uk-margin-auto-vertical uk-flex-between">
        <div class="uk-card uk-card-large uk-margin-large-top uk-width-1-1 uk-width-1-2@l">
            <div class="uk-card-header">
                <h3 class="uk-card-title">{% trans %}Login{% endtrans %}</h3>
            </div>

            <div class="uk-card-body">

                {% if error %}
                    <div class="uk-alert-danger" uk-alert>
                        <a class="uk-alert-close" uk-close></a>
                        <p>{{ error.messageKey|trans(error.messageData, 'security') }}</p>
                    </div>
                {% endif %}

                <form action="{{ path('login') }}" method="post">
                    <fieldset class="uk-fieldset">
                        <div class="uk-margin">
                            <div class="uk-form-label">{% trans %}Email{% endtrans %}</div>
                            <div class="uk-inline uk-width-1-1">
                                <span class="uk-form-icon" uk-icon="icon: user"></span>
                                <input class="uk-input" type="text" name="_username" value="{{ last_username }}" placeholder="user@example.com" />
                            </div>
                        </div>

                        <div class="uk-margin">
                            <div class="uk-form-label">{% trans %}Password{% endtrans %}</div>
                            <div class="uk-inline uk-width-1-1">
                                <span class="uk-form-icon" uk-icon="icon: lock"></span>
                                <input class="uk-input" type="password" name="_password" />
                            </div>
                        </div>





                        <div class="uk-margin uk-grid">
                            <div class="uk-inline uk-width-1-1 uk-width-1-2@s">
                                <input class="uk-checkbox" type="checkbox" name="_remember_me" />
                                <div class="uk-form-label uk-inline">{% trans %}Remember me{% endtrans %}</div>
                            </div>
                            <div class="uk-inline uk-width-1-1 uk-width-1-2@s">
                                <input type="submit" class="uk-button uk-width-1-1 uk-button-primary" value="{% trans %}Login{% endtrans %}" />
                            </div>

                        </div>

                    </fieldset>


                    <input type="hidden" name="_csrf_token"
                           value="{{ csrf_token('authenticate') }}"
                    >
                </form>



            </div>

        </div>
        <div class="uk-visible@l uk-width-1-2 uk-background-contain uk-height-large uk-margin-large-top" style="background-image: url({{ asset('images/undraw_my_password_d6kg.svg') }});"></div>
    </div>


{% endblock %}

{% block body2 %}


    {% if error %}
        <div>{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    <form action="{{ path('login') }}" method="post">
        <label for="username">Username:</label>
        <input type="text" id="username" name="_username" value="{{ last_username }}"/>

        <label for="password">Password:</label>
        <input type="password" id="password" name="_password"/>

        <input type="hidden" name="_csrf_token"
               value="{{ csrf_token('authenticate') }}"
        >

        <button type="submit">login</button>
    </form>
{% endblock %}